test("this test will fail", () => {
  fail("This is an intentional failure");
});
